# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats

# read the csv file.
consumer_income_df = pd.read_csv('/content/consumer_income.csv')
# print the head.
print('The header of the given data: ')
print(consumer_income_df.head())
print()
# print the info
print('The info of the given data:')
print(consumer_income_df.dtypes)
print()
# print the descriptive statistics.
print('The descriptive statistics: ')
print(consumer_income_df.describe())
print()

#Remove the records with missing data by using a drop method.
consumer_income_df_no_null = consumer_income_df.dropna()
print(consumer_income_df_no_null)

"""In the descriptive statistics, the total no of rows present in the dataset is 2240. And in the consumer_income_data_no_null data the total no of rows are 2239.
This implies that there is one row with null value.
"""

# Create two subsets of data, one that includes married consumers and one that includes single
# consumers. (Don’t include the other marital status categories in either subset.)
consumer_income_df_no_null_single = consumer_income_df_no_null[consumer_income_df_no_null['Marital_Status'] == 'Married']
consumer_income_df_no_null_married = consumer_income_df_no_null[consumer_income_df_no_null['Marital_Status'] == 'Single']

#  Generate descriptive statistics of the two types of consumers.
print('The descriptive statistics for married: ')
print(consumer_income_df_no_null_married.describe())
print()
print('The descriptive statistics for single: ')
print(consumer_income_df_no_null_single.describe())
print()

# Generate box plots showing the comparison of income for married vs single consumers
fig1,ax1 = plt.subplots()
ax1.set_title("comparison of income for married vs single consumers")
ax1.boxplot([consumer_income_df_no_null_married['Income'].values,consumer_income_df_no_null_single['Income'].values])
ax1.set_ylabel("Income")
ax1.set_xticklabels(['Married','Single'])
plt.show()
print()

# Formulate a hypothesis based on the research question of whether there is a significant difference
# between the incomes, number of children at home, and numbers of teens at home for married
# consumers compared to single consumers. Use a significance level of 0.05. Print and label your
# hypotheses using print functions so they display in the output window.

print('For Income:')
print('H0: There is no significant difference between the incomes,\n'
 ' for married consumers compared to single consumers')
print()
print('H1: There is a significant difference between the incomes,\n'
 ' for married consumers compared to single consumers')
print()

# Conduct t-test
print('T-test results for difference between the incomes,\n'
 'for married consumers compared to single consumers')
print(scipy.stats.ttest_ind(consumer_income_df_no_null_married['Income'], consumer_income_df_no_null_single['Income']))
print()
print('Since the p-value for income is greater than 0.05, we fail to reject the null hypothesis\n'
'and conclude that there is no significant difference between the incomes,\n'
 ' for married consumers compared to single consumers ')
print()

print('For number of children:')
print('H0: There is no significant difference between number of children at home,\n'
 ' for married consumers compared to single consumers')
print()
print('H1: There is a significant difference between number of children at home,\n'
 ' for married consumers compared to single consumers')
print()

# conduct t-test
print('T-test results for difference between number of children,\n'
 'for married consumers compared to single consumers')
print(scipy.stats.ttest_ind(consumer_income_df_no_null_married['Kidhome'], consumer_income_df_no_null_single['Kidhome']))
print()
print()
print('Since the p-value for number of children is greater than 0.05, we fail to reject the null hypothesis\n'
'and conclude that there is no significant difference between the number of children,\n'
 ' for married consumers compared to single consumers ')
print()

print('For number of teens:')
print('H0: There is no significant difference between  numbers of teens at home,\n'
 ' for married consumers compared to single consumers')
print()
print('H1: There is a significant difference between  numbers of teens at home,\n'
 ' for married consumers compared to single consumers')
print()
# conduct t-test
print('T-test results for difference between numbers of teens at home,\n'
 'for married consumers compared to single consumers')
print(scipy.stats.ttest_ind(consumer_income_df_no_null_married['Teenhome'], consumer_income_df_no_null_single['Teenhome']))
print()
print('Since the p-value for number of teens is lesser than 0.05, we reject the null hypothesis\n'
'and conclude that there is significant difference between the number of teens,\n'
 ' for married consumers compared to single consumers ')